### ISSUE TITLE
cannot find position

### ISSUE THREAD

**Issue by scampi** [syohex/byzanz-window#5]
I get the following error (error code is 1) when I click on a window. My window manager is I3.

```
❯ byzanz-window --duration=10 --delay=5 --cursor output.gif
Select the window which you like to capture.
can't find 'position'
```

**Comment by syohex** [comment]
Could you show me output of `xprop -id $some_window_id` ? You can get `$some_window_id` by `xdotool selectwindow` and click some window(then output window id to stdout).

**Comment by scampi** [comment]
```sh
~
❯ xdotool selectwindow
33554435

~
❯ xprop -id 33554435
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		window id # of group leader: 0x2000001
XdndAware(ATOM) = BITMAP
_NET_WM_OPAQUE_REGION(CARDINAL) = 7, 0, 437, 7, 0, 7, 451, 722
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 33554437, 33554438
_NET_WM_USER_TIME(CARDINAL) = 336237550
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x2000004
WM_CLIENT_LEADER(WINDOW): window id # 0x2000001
_NET_WM_PID(CARDINAL) = 17271
WM_LOCALE_NAME(STRING) = "en_IE.UTF-8"
WM_CLIENT_MACHINE(STRING) = "troy"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 9 by 15
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "termite", "Termite"
WM_ICON_NAME(STRING) = "~"
_NET_WM_ICON_NAME(UTF8_STRING) = "~"
WM_NAME(STRING) = "~"
_NET_WM_NAME(UTF8_STRING) = "~"
```

**Comment by syohex** [comment]
Hmm, i3 does not support ` _NET_FRAME_EXTENTS ` yet.

- https://github.com/i3/i3/issues/1335
- https://github.com/i3/i3/issues/1341

**Comment by syohex** [comment]
How about this patch ? We cannot retrieve window frame information on i3 window manager because it does not support `_NET_FRAME_EXTENTS`. Applying following patch make byzanz-window ignore window frame.

```patch
diff --git a/cmd/byzanz-window/byzanz-window.go b/cmd/byzanz-window/byzanz-window.go
index a6d8935..dcd9573 100644
--- a/cmd/byzanz-window/byzanz-window.go
+++ b/cmd/byzanz-window/byzanz-window.go
@@ -117,7 +117,7 @@ func getWindowInformation(winid int) (*byzanzArg, error) {
 
 	match = posRe.FindStringSubmatch(string(xproperty))
 	if match == nil {
-		return nil, errors.New(`can't find 'position'`)
+		match = []string{"0", "0", "0", "0", "0"}
 	}
 
 	left, err := strconv.ParseInt(match[1], 10, 32)

```

**Comment by scampi** [comment]
This works well for me!

**Comment by syohex** [comment]
I have applied workaround at #6.
Please report me if you still have any issues.

Thanks for reporting issue.

**Comment by scampi** [comment]
Sure. Thanks for this project, it is perfect with byzanz-record.

**Comment by vire** [comment]
@syohex Could you plase make a new release a new binary with this fix? I'm using also i3 and with the downloaded binary I gent the same error as this issue states, but when i `go get` this repo the downloaded binary works fine

**Comment by syohex** [comment]
https://github.com/syohex/byzanz-window/releases/tag/v0.0.2

I tagged and update binary file. Please check it.

**Comment by Airblader** [comment]
I've stumbled across this issue for something entirely unrelated, but just wanted to throw in that the specifications would require you to read `_NET_SUPPORTED` to check for compliance.
