### ISSUE TITLE
Version flag

### ISSUE THREAD

**Issue by KabbAmine** [syohex/byzanz-window#7]
Hi, thanks for this little application.

Can we have a version flag (`-v` or `-V`) ? It will be very useful for those who install/update apps via scripts (Like myself).

**Comment by syohex** [comment]
Done by https://github.com/syohex/byzanz-window/commit/4a6b44a00d9d6fba94f827ce6dc6ffa59b9a68e9
Thanks for suggestion

**Comment by KabbAmine** [comment]
That was quick, thanks.

I'm using the binaries, so I'll wait for the next release.

**Comment by syohex** [comment]
https://github.com/syohex/byzanz-window/releases/tag/v0.1.0

Update new version.
